MODULE := M2MEventLoop
CFLAGS += -I../nanostack-event-loop -I../nanostack-event-loop/platform -I../../Util/Include -I../../ns-hal-pal
#CFLAGS += -I../../sal-stack-nanostack-eventloop/nanostack-event-loop -I../../ns-hal-pal

include $(RIOTBASE)/Makefile.base

