MODULE := M2MSec
CFLAGS += -I../mbed-client-dtls -I../../ -I../../mbed-client-riot/mbed-client-riot -I../../../mbed-coap/mbed-coap
CFLAGS += -I../../../ -I../../../mbed-trace -I../../../Util/Include -I../../../mbedtls/include/mbedtls
CFLAGS += -I../../../sal-stack-nanostack-eventloop/nanostack-event-loop

include $(RIOTBASE)/Makefile.base
