MODULE := PAL
CFLAGS += -I../include -I../../mbed-trace -I../../Util/Include
#CFLAGS += -I../../sal-stack-nanostack-eventloop/nanostack-event-loop -I../../ns-hal-pal

include $(RIOTBASE)/Makefile.base