MODULE := M2M
CFLAGS += -I../../Util/Include -Iinclude -I../ -I../../mbed-trace

#CFLAGS += -I../../sal-stack-nanostack-eventloop/nanostack-event-loop -I../../ns-hal-pal

include $(RIOTBASE)/Makefile.base
