MODULE := M2MHAL
CFLAGS += -I../sal-stack-nanostack-eventloop/nanostack-event-loop -I../sal-stack-nanostack-eventloop/nanostack-event-loop/platform
CFLAGS += -I../Util/Include -I../sal-stack-nanostack-eventloop/source -I../mbed-trace

include $(RIOTBASE)/Makefile.base