MODULE := M2MRIOT

CFLAGS += -I../../../Util/Include -Iinclude -I../mbed-client-riot -I../../../sal-stack-nanostack-eventloop/nanostack-event-loop -I../../../mbed-trace
CFLAGS += -I../../ -I../../../ns-hal-pal -I../../../mbed-coap/mbed-coap -I../../../mbed-client-pal/include

include $(RIOTBASE)/Makefile.base
