MODULE := M2MUTIL
CFLAGS += -IInclude -I../sal-stack-nanostack-eventloop/nanostack-event-loop -I../mbed-client-randlib/mbed-client-randlib 
CFLAGS += -I../ns-hal-pal
#CFLAGS += -I../../sal-stack-nanostack-eventloop/nanostack-event-loop -I../../ns-hal-pal

include $(RIOTBASE)/Makefile.base
