MODULE := M2M
CFLAGS += -I../ -I../../mbed-coap/mbed-coap -I./ -I../../Util/Include -I../../mbed-trace/
CFLAGS += -I../../sal-stack-nanostack-eventloop/nanostack-event-loop -I../../ns-hal-pal

include $(RIOTBASE)/Makefile.base
